//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineJobApplication.App_Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_1526890_onlinejobEntities : DbContext
    {
        public db_1526890_onlinejobEntities()
            : base("name=db_1526890_onlinejobEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<CareerArea> CareerAreas { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<Religion> Religions { get; set; }
        public virtual DbSet<Stage> Stages { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserJobApplication> UserJobApplications { get; set; }
        public virtual DbSet<UserJobApplicationStage> UserJobApplicationStages { get; set; }
        public virtual DbSet<Email> Emails { get; set; }
    }
}
