//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineJobApplication.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserJobApplication
    {
        public int Id { get; set; }
        public int JobId { get; set; }
        public int UserId { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual User User { get; set; }
    }
}
